- .babelrc
- package.json
- src/index.js
- test/index.js
> Adding add-module-exports Babel es-lint plugin

- src/utils.js
small fix regarding @mtrunkat feedback
> move client user-agent to constant

- .gitignore
- package.json
- src/request_queues.js
> Feature/updates - updates packages + fixes code coverage

- src/utils.js
I would consider:
* logging it just as debug
* logging only requests failed 3/4*expBackOffMaxRepeats times not 1/2*expBackOffMaxRepeats
to decrease number of logs
> Logging requests that failed 4times

- CHANGELOG.md
- src/index.js
- src/utils.js
- test/_helper.js
- test/utils.js
I think the index in the array is wrong
> Fixed bug in rate limit stats

- CHANGELOG.md
- package.json
- src/datasets.js
- src/key_value_stores.js
- src/request_queues.js
- test/datasets.js
- test/key_value_stores.js
- test/request_queues.js
This is needed for storage renaming
> Adding update method for all storage types

- README.md
- docs/README.hbs
- docs/build_docs.js
- docs/helpers.js
- docs/partials/header.hbs
- src/resource_clients/key_value_store.js
Really don't know if it's gonna be worth the effort, but I've cobbled together this anchor-adding template.
The only thing (I think) I can't figure out is in the comment
> Add anchors to headings in template

- CHANGELOG.md
- package.json
- src/http_client.js
- test/_helper.js
Max limits on body size prevented uploads of large files via `kvs.setRecord`
> Remove body limits

- src/interceptors.js
- src/resource_clients/actor.js
- src/resource_clients/task.js
- test/actors.test.js
- test/tasks.test.js
> feat: add function serialization to actor input

- CHANGELOG.md
- package.json
- src/resource_clients/run.js
Added gracefully parameter for abort run function
> Abort run: Added gracefully param

- CHANGELOG.md
- package.json
- src/resource_clients/webhook.js
- test/mock_server/routes/webhooks.js
- test/webhooks.test.js
Add method to run webhook test;
Should this method be added to the python package? @drobnikj
> Add method to run webhook test

- src/apify_client.ts
- src/base/resource_client.ts
- src/resource_clients/actor.ts
- src/resource_clients/build.ts
- src/resource_clients/dataset.ts
- tsconfig.json
For https://github.com/apify/apify-ts/pull/4
> chore: make Datasets support generics

- CHANGELOG.md
- src/resource_clients/actor.ts
- src/resource_clients/actor_collection.ts
- src/resource_clients/build.ts
- src/resource_clients/dataset.ts
- src/resource_clients/key_value_store.ts
- src/resource_clients/request_queue.ts
- src/resource_clients/schedule.ts
- src/resource_clients/task.ts
- src/resource_clients/webhook.ts
- src/resource_clients/webhook_dispatch.ts
> fix: fields ending in `At` are Date objects

- src/interceptors.ts
> fix: add missing override modifier for error cause

- src/base/resource_client.ts
- src/resource_clients/actor.ts
Fixes #253 (I used the wrong type before 😅)
> fix(ActorRun): correct type for `status` field

- src/resource_clients/request_queue.ts
Adjusted parallels and unprocessed retries for batch add requests.
> chore: adjust parallels and unprocessed retries for batch add requests

- CHANGELOG.md
- package.json
- src/resource_clients/actor.ts
- src/resource_clients/run.ts
Link to API docs missing - the endpoint is not documented yet.
> feat: statusMessage method using the new API endpoint

- src/resource_clients/actor.ts
Part of [apify-core@7407](https://github.com/apify/apify-core/issues/7407).
Update Actor types, update fields to match [API reference](https://docs.apify.com/api/v2#/reference/actors/version-collection/update-actor) and allow partial typecheck for actor-related console calls.
> feat: update actor types

- src/resource_clients/dataset.ts
Waiting on https://github.com/apify/apify-core/pull/7537
See https://www.notion.so/apify/Dataset-fields-param-for-nested-fields-0df789303ed84faa85edf3b3cde818f0#54451f44c7944ae9980743467213d6a9
> feat: Add flatten param to Dataset items listing

- src/index.ts
> feat: re-export useful types and classes

- src/apify_client.ts
- src/resource_clients/dataset.ts
> fix(types): correct extends clause for Dataset entries

- website/docusaurus.config.js
- website/src/pages/index.js
Looks like this now, following the content from the Notion page:
> feat: landing page update

- src/resource_clients/actor.ts
- src/resource_clients/run_collection.ts
see https://github.com/apify/apify-core/issues/8077 for context
Plus I found some missing attrs, which we have in API but not in types and not in API ref.
> fix(actor): fix types for actor run

- src/http_client.ts
- src/utils.ts
Closes https://github.com/apify/apify-client-js/issues/235
> fix: improve reading of the version when using bundlers

- src/resource_clients/actor.ts
- src/resource_clients/build.ts
- src/resource_clients/build_collection.ts
Improve types based on API changes
> feat(runs, builds): add usage usd into actor run and build types

- src/apify_client.ts
- src/index.ts
- src/resource_clients/store_collection.ts
- test/mock_server/routes/store.ts
- test/mock_server/server.js
- test/store.test.ts
New method for listing Actors in store
See API reference https://docs.apify.com/api/v2/#/reference/store
> feat: Added StoreCollectionClient class useful for listing Actors in Apify Store

- src/resource_clients/webhook.ts
- src/resource_clients/webhook_collection.ts
> feat: add new webhook fields

- package-lock.json
- package.json
- src/resource_clients/request_queue.ts
> chore(request-queue): use const from shared

- .github/workflows/docs.yaml
Smartlook token for docs build
> docs: add smartlook token to docs build

- .github/workflows/docs.yaml
Smartlook token for apify-client-js docs.
> feat: Add smartlook token to docs build [internal]

- docs/examples/index.md
- website/docusaurus.config.js
- website/sidebars.js
- website/versioned_docs/version-2.9/examples/index.md
- website/versioned_sidebars/version-2.9-sidebars.json
Part of apify/apify-web#3616
In the end I joined getting latest data and merging datasets.
> feat: JavaScript client code examples for platform

- package.json
- src/resource_clients/actor.ts
- src/resource_clients/actor_collection.ts
- src/resource_clients/task.ts
This PR adds types for Actor Standby.
> feat: add Actor Standby types

- src/resource_clients/dataset.ts
- src/resource_clients/key_value_store.ts
- src/resource_clients/request_queue.ts
Related https://github.com/apify/apify-cli/pull/685
> fix: allow `null` when updating dataset/kvs/rq `name`

- src/resource_clients/actor.ts
- src/resource_clients/build.ts
The API was updated, based on changes we updated the types in client:
- add actorDefinitions for build detail
- deprecate inputSchema and readme
> feat(actor-build): add actorDefinition type for actor build detail, deprecate inputSchema and readme.

- .github/workflows/pre_release.yaml
- .github/workflows/release.yaml
> ci: Use correct ref for NPM publishing

- src/resource_clients/actor.ts
- test/actors.test.js
- test/mock_server/routes/actors.js
This PR adds `defaultBuild()` method to Actor client
> feat: add defaultBuild method

- src/resource_clients/build.ts
This PR fixes documentation link
> chore: fix openapi documentation link

- src/resource_clients/actor.ts
Related: https://apify.slack.com/archives/C010Q0FBYG3/p1747042200680909
> docs: improve docs for `waitForFinish` in `Actor.start`

- website/package-lock.json
- website/package.json
fixes incorrect package version combination
> fix: sync `@docusaurus` dependencies version [internal]
