CHANGELOG.md, package.json, src/datasets.js, test/datasets.js
Allows strings as data to `putItems()` to support large payload chunking.
See: https://github.com/apifytech/apify-js/pull/138
=> Add support for serialized data (strings) in datasets.putItems()

src/utils.js, test/utils.js
Adds HTML and XML to `parseBody()`
to fix: https://github.com/apifytech/apify-js/issues/130
and support: https://github.com/apifytech/apify-js/pull/140
=> Add support for parsing HTML and XML

src/datasets.js, test/datasets.js
I should probably add some tests that it really retries those errors. Is there a way how to stub the requestPromise function?
=> Bug fix: Dataset Exponential Backoff

CHANGELOG.md, package.json, src/index.js, src/utils.js, test/_helper.js, test/utils.js
Rate limit errors (429) are now tracked per retry:
```
[
9, <- 9x on initial request
3, <- 3x on first retry
1, <- 1x on second retry
0, <- no 429s on third retry
...etc
]
```
=> Track rate limit errors per number of retries

CHANGELOG.md, package.json, src/resource_clients/key_value_store.js, test/key_value_stores.test.js
I found this problem during testing API. Before v1 released Apify query parameters were not included in direct upload URL calls.
=> Fixed: Omits query params for direct upload URL calls

src/resource_clients/dataset_collection.js, src/resource_clients/key_value_store_collection.js, src/resource_clients/request_queue_collection.js
`ow` argument checks were missing which caused weird errors when `{ name }` instead of `name` was provided.
=> Add missing getOrCreate validations

CHANGELOG.md, package.json, src/http_client.js
Thanks to a [bug in `axios`](https://github.com/axios/axios/issues/2829) downloading of large responses was extremely slow. Using a `-1` instead of `Infinity` as `maxContentLength` fixes the problem.
=> fix: slowdown for big responses

CHANGELOG.md, src/index.js
=> chore: add non-empty ID validation to resource clients

CHANGELOG.md, package.json, src/base/resource_client.js, src/index.js, src/resource_clients/actor.js, src/resource_clients/key_value_store.js, src/resource_clients/run_collection.js, src/resource_clients/task.js, test/users.test.js, webpack.config.js
Updates `apify-shared` to use only the needed packages (`log` and `consts`).
=> chore: update apify-shared

src/resource_clients/actor_version.ts
The source code and source files types both have the `source(Code|Files)` properties present
=> fix: correct type for actor versions

src/base/api_client.js, src/base/resource_client.js, src/base/resource_collection_client.js, src/resource_clients/actor.js, src/resource_clients/build.js, src/resource_clients/dataset.js, src/resource_clients/key_value_store.js, src/resource_clients/log.js, src/resource_clients/request_queue.js, src/resource_clients/run.js, src/resource_clients/schedule.js, src/resource_clients/task.js, src/resource_clients/webhook.js, test/actors.test.js
I get back `this._params(options) because without it the internal sub-clients didn't get params from the parent client.
Sadly tests were not cover this case, so I updated the lastRun test to cover this case.
This reverts commit c766a50
=> fix: revert back passing params using ApifyClient _params method

package.json, src/http_client.ts
We need to pass this header from the worker env variable in order to be able to associate runs spun as a part of one flow.
=> feat: Adding x-apify-workflow-key header

src/resource_clients/actor.ts, src/resource_clients/task.ts, src/utils.ts
While working on https://github.com/apify/apify-ts/pull/11, I noticed a lot of duplicated types that can be united and re-used in the SDK
This PR corrects some of them. I will submit more PRs as I find them necessary
=> chore: fix some annoying types

CHANGELOG.md, package.json, src/base/resource_collection_client.ts, test/datasets.test.js, test/key_value_stores.test.js, test/request_queues.test.js
Thanks to a change in API, we could not create unnamed storages with the Client anymore. This fixes it.
=> fix: unnamed storages

CHANGELOG.md, package.json, src/resource_clients/actor.ts, src/resource_clients/key_value_store.ts, src/resource_clients/task.ts, test/tasks.test.js
I'm not entirely sure if this is a breaking change or not, so I'm awaiting your thoughts on it. This PR aligns types closer to what the API wants as well as relaxes the types for KeyValueStore#getRecord.
I have the changelog prepared, just have to change the version number once I know which is the correct one to change it to
=> fix: correct validation for Task call & start, and loosen up KeyValueStore getRecord options

src/resource_clients/dataset.ts
I'm working on adding the `view` parameter to the dataset items API, and it would help me out if I could use it from the client instead of having to call the API manually.
=> feat: Add support for the `view` parameter in dataset items client

CHANGELOG.md, src/apify_client.ts, src/resource_clients/request_queue.ts, test/request_queues.test.js
The default timeout for API client (360 secs) is too high for some endpoints. Add an option to set timeout to request queue separately from the main API client timeout.
=> feat: add option to set timeout for request queue client

src/resource_clients/task_collection.ts
Closes #227, and resolves one of the issues mentioned in #229 
Awaiting response in Slack to see if the actId should also be allowed in TaskUpdateData or not
=> fix(typings): correct types and validation for `tasks().create`

README.md, src/interceptors.ts
Fixing incorrect type for run collection list status. For more info: https://apifier.slack.com/archives/C0L33UM7Z/p1646217864275879
Had to do it manually as the `build_docs` script is not working see issue: 
https://github.com/apify/apify-client-js/issues/236
=> chore: updated incorect RunCollectionClient list status type

src/resource_clients/actor.ts, src/resource_clients/task.ts
Params are needed to finish [this task](https://github.com/apify/apify-core/issues/6313)
API already accepts these params ([PR](https://github.com/apify/apify-core/pull/6452))
=> feat: origin param added for last actor/task run endpoints

src/resource_clients/request_queue.ts, src/utils.ts, test/mock_server/routes/request_queues.js, test/request_queues.test.js
* New method to list requests
* New method to easily iterate all requests in queue
Example usage:
```
for await (const { items } of rqClient.paginateRequests()) {
const rqsToDelete = items.filter(someFilter);
await rqClient.batchDeleteRequests(rqsToDelete);
}
```
=> feat: add request queue requests list method

README.md, package.json, src/http_client.ts, src/resource_clients/key_value_store.ts
As discussed in https://apifier.slack.com/archives/CD0SF6KD4/p1655891141193099
I'm still not completely convinced it is ok to switch the default behavior like this - maybe a warning could be issued for a few versions when a stream is passed for the first time during a run
Also any ideas on how to test this are welcome, but what I was doing so far is just run it with a stream of a biig (500 MB+) file and then observe memory usage of the `node` process
=> Support streaming request body

src/resource_clients/actor_version.ts
Single file has been long deprecated and we want to get rid of it across codebase.
Theoretically this is a breaking change, but not sure if we have to treat it as such (due to long deprecation).
=> feat: drop single file support

src/utils.ts, test/utils.test.js
We also want to return `undefined` when getting resources when we get a `record-or-token-not-found` error in addition to `record-not-found` errors.
=> chore: add custom catching logic for `record-or-token-not-found` errors

src/resource_clients/actor.ts, src/resource_clients/task.ts
=> fix: `Actor.call` and `Task.call` accept `waitSecs` not `waitForFinish`

src/http_client.ts
The headers we thought we were passing were thrown away few lines afterwards.
I've only kept the `x-apify-workflow-key` header and dropped the `accept` one (it works without it).
=> fix: correctly set default client headers

package-lock.json, package.json, src/apify_client.ts
The `apify-client` package now provides a `setStatusMessage` method compliant with the newest `@crawlee/types` release.
=> feat: add "standard" handing for setStatusMessage

.github/workflows/docs.yaml, .github/workflows/release.yaml
This uses new secrets set on organization level instead of the repo-level secrets.
=> chore: Use new workflow secrets

.github/workflows/docs.yaml
This makes sure that the CloudFront cache is invalidated after the docs are deployed to GitHub pages.
=> chore: invalidate CloudFront cache after docs deploy

src/resource_clients/webhook.ts
This PR adds `shouldInterpolateStrings` field to webhook.
=> feat: add shouldInterpolateStrings field to webhook type

website/docusaurus.config.js
The new subtitle fits the Python version and the current `<title>` tags.
=> docs: change subtitle

src/resource_clients/schedule.ts, src/utils.ts
`ScheduleUpdateData` enforces `id` key on `actions` prop, but it should be optional.
Following snippet should be OK:
```ts
await client.schedule(schedule.id).update({
actions: [{
type: ScheduleActions.RunActor,
actorId: 'someId',
}]
});
```
But I get this error:
```
Type '{ type: ScheduleActions.RunActor; actorId: string; }' is not assignable to type 'ScheduleAction'.
Property 'id' is missing in type '{ type: ScheduleActions.RunActor; actorId: string; }' but required in type 'ScheduleActionRunActor'.ts(2322)
schedule.d.ts(47, 5): 'id' is declared here.
```
=> fix: ScheduleUpdateData type

src/resource_clients/schedule.ts, src/utils.ts
This PR appears to follow-up on https://github.com/apify/apify-client-js/pull/276 which made it so `id` was optional ✅ but did so in a way that removed the remainder of the required fields from the type definition ❌, e.g. `actorTaskId` was no longer recognized as a valid property as of v2.8.2
Because `ScheduleAction` is defined as a union of different types, we must use [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) to capture the specific properties of the individual subtypes correctly.
=> fix(schedule): expose other fields when id optional

src/http_client.ts, src/resource_clients/key_value_store.ts, src/resource_clients/log.ts, src/utils.ts, website/versioned_docs/version-2.8/api-typedoc.json
The first one is from DOM, the latter - Node. Also, added type for URLSearchParams arg as it's different in Node and won't accept string[][].
Tested by running build script and commenting out DOM in tsconfig libs
Closes #240
=> fix: replace ReadableStream with Readable

src/resource_clients/request_queue.ts, src/utils.ts, test/request_queues.test.js
=> feat(request-queue): Limit payload size for batchAddRequests()

package.json
For some unknown reason, we stopped publishing it in v2.0.1
=> fix: publish browser bundle

src/resource_clients/key_value_store.ts, src/utils.ts, test/key_value_stores.test.js
=> feat: add `KeyValueStore.recordExists()` method

src/resource_clients/build.ts, test/builds.test.js, test/mock_server/routes/builds.js
This wraps the new `/actor-builds/<BUILD_ID>/log` API.
=> feat: add log() method to BuildClient (JS)

src/apify_client.ts, src/resource_clients/build_collection.ts, src/resource_clients/run_collection.ts, test/builds.test.js, test/mock_server/routes/builds.js, test/mock_server/routes/runs.js, test/runs.test.js
=> feat: add `runs()` and `builds()` top level endpoints

src/resource_clients/user.ts, test/mock_server/routes/users.js, test/users.test.js
These endpoints have been around for some quite time and now we're exposing them via the JS client.
=> feat: add monthlyUsage() and limits() endpoints to UserClients

src/resource_clients/user.ts, src/utils.ts, test/utils.test.js
This field does not end with "At", which means it is ignored by the existing parseDateFields helper. This PR adjusts this helper to support parsing other fields as well.
To avoid accidental braking changes by applying the new parser on all existing data structures, the helper now has a new optional shouldParseField() param to identify other fields to be parsed. Without this param, the helper behaves just like before.
The actual user-facing change (`typeof monthlyUsage.dailyServiceUsages[].date === Date`) was tested manually and will be covered by the integration tests in `apify-core`.
=> feat: parse monthlyUsage.dailyServiceUsages[].date as Date

src/utils.ts
This is polluting logs as there are data structures in API responses that have arbitrary depth (user data, data sets).
Context:
https://apifier.slack.com/archives/CGZSN9DQC/p1708707905914559
=> chore: remove warning when parseDateFields reaches depth limit

src/resource_clients/webhook.ts
This PR adds a missing field on the `Webhook` interface. As per the [documentation](https://docs.apify.com/platform/integrations/actors/integrating-actors-via-api), one can programmatically integrate actors together using the "create webhook" endpoint. The `isApifyIntegration` field helps the UI distinguish whether to render it as an ordinary HTTP webhook in the Apify console.
=> fix: add missing `isApifyIntegration` field to `Webhook` type

src/resource_clients/schedule.ts
Related to https://github.com/apify/apify-core/issues/15493
Adds a `notifications` field to the schedule, so that users can set whether they get notified when their scheduled run fails to start. 
The `notifications` object only has an `email` field for now, but we might want UI notifications at some point in the future, so I've done it this way.
From what I could find, this is all that needs doing, right? 
[This PR](https://github.com/apify/apify-core/pull/15693/files#diff-e443dce6de418714e39866eb1a4ca59f7d4ce49dcbc5cdc692ea07e1be36bacfR436) will add the bit that sends the notification
=> feat: add notifications field to Schedule

docs/index.md, website/versioned_docs/version-2.9/index.md
I noticed there was a typo for 3 examples so I fixed that and unified the naming across code examples
=> docs: Fixed typos for the client init and unified it across the code examples

src/apify_api_error.ts, test/apify_api_error.test.js, test/mock_server/routes/add_routes.js
This update is needed because in API we will be adding a new data field to the API error, which will be used during dataset validation.
https://github.com/apify/apify-docs/pull/1079
=> feat: added data property to API error object

src/resource_clients/dataset.ts
We're adding an option to unwind multiple fields when listing the dataset items. This adds an option to `DatasetClient` to pass those multiple fields in the `unwind` parameter.
=> feat: allow `unwind` param to `DatasetClient.listItems()` to be an array

website/docusaurus.config.js, website/package-lock.json, website/package.json, website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Bumps the Docusaurus version to v3 and swaps the `docusaurus-plugin-typedoc-api` for our updated fork.
=> docs: bump docusaurus to v3

src/resource_clients/user.ts, test/mock_server/routes/users.js, test/users.test.js
Resolves #329 - add `updateLimits` function to `UserClient`, which does `PUT: /v2/users/:userId/limits`
Api docs PR here: https://github.com/apify/openapi/pull/103
Endpoint is already implemented, only api docs and client was missing
=> feat: add user.updateLimits

package-lock.json, package.json, src/apify_client.ts, src/http_client.ts, src/utils.ts, test/http_client.test.js
Related https://github.com/apify/apify-sdk-js/issues/331
=> feat: allow appending custom parts to the user agent

.github/workflows/pre_release.yaml, .github/workflows/release.yaml, CHANGELOG.md, package.json
This is essentially the same thing that we do in apify/apify-sdk-python, apify/crawlee-python, etc., but for Javascript.
=> ci: Automate the release process

src/resource_clients/actor.ts
I have no idea why we had such a wrong type there.
1. There doesn't have to be `latest` tag
2. Tags are arbitrary strings
=> fix(actor): correctly set type for ActorTaggedBuilds

src/resource_clients/request_queue.ts
Based on latest changes in API, updating type for RequestQueueClientListAndLockHeadResult.
* `queueHasLockedRequests` - newly added parameter in response
* `clientKey` - this was there in past, just missing in type
=> feat(request-queue): Add queueHasLockedRequests and clientKey into RequestQueueClientListAndLockHeadResult

src/resource_clients/build.ts
It should be `actorDefinition` instead of `actorDefinitions`
I've checked in db and by calling:
```
curl -L 'https://api.apify.com/v2/actor-builds/Nxeu6qxhoEs90eHIH' \
-H 'Accept: application/json'
```
Response
```
"gitBranchName": "master",
"actorDefinition": {
"actorSpecification": 1,
"name": "rag-web-browser",
"title": "RAG Web browser",
```
=> fix: change type `Build.actorDefinitions` to `Build.actorDefinition`

src/resource_clients/dataset.ts, test/datasets.test.js, test/mock_server/routes/datasets.js
Part of https://github.com/apify/apify-core/issues/18807 - Implementation of new API endpoint `v2/datasets/{datasetId}/statistics`
=> feat: add dataset.statistics

test/_helper.js
I cannot find root cause, I'm adding log, once it fails again it should help to debug.
=> test: Add debug log, to see why test randomly failed

src/resource_clients/build.ts, test/builds.test.js, test/mock_server/routes/builds.js
Recently we've introduced new endpoint:
- `/v2/actor-builds/:buildId/openapi-specification`
**This PR adds this endpoint to BuildClient**
P.S. The link to the documentation is correct, but docs are not yet merged into production. I'll merge this PR after the docs are merged.
=> feat: added getOpenApiSpecification() to BuildClient

src/resource_clients/build.ts, test/builds.test.js, test/mock_server/routes/builds.js
Recently, we created new endpoints:
`/v2/acts/:actorId/builds/:buildId/openapi-specification`
`/v2/actor-builds/:buildId/openapi-specification`
Than we've received a feedback to rename endpoints to `/openapi.json`.
**This PR renames OpenAPI endpoints from `*/openapi-specification` to `*/openapi.json`*
More context [here](https://apify.slack.com/archives/C01VBUV81UZ/p1737975106009729)
=> refactor: rename /openapi -> /openapi.json

package-lock.json, package.json, src/resource_clients/actor.ts, src/resource_clients/dataset.ts, src/resource_clients/key_value_store.ts, src/resource_clients/request_queue.ts, src/resource_clients/run.ts
We plan to allow users to configure through API & clients how their storages and runs can be accessed — whether just the ID / name is sufficient to access the storage. This is controlled through the `generalAccess` resource property, which overrides account setting for the resource.
Full context in https://github.com/apify/apify-core/issues/19012.
This PR updates the client so that it can be used to get and update general access on datasets, key-value stores, request queues, and runs.
```typescript
const run = client.run(runId);
// Set general access to ANYONE_WITH_ID_CAN_READ which overrides the account setting.
await run.update({ generalAccess: RUN_GENERAL_ACCESS.ANYONE_WITH_ID_CAN_READ });
// Reset the general access so that it follows the account setting.
await run.update({ …
```
=> feat: add support for general resource access

src/resource_clients/actor.ts, test/actors.test.js, test/mock_server/routes/actors.js
This PR updates the Actor.defaultBuild() method to return a BuildClient instance instead of a raw response object.
=> fix: defaultBuild() returns BuildClient

src/resource_clients/run_collection.ts
Fixes the problem with invalid type `RunCollectionListOptions` of `RunCollectionClient.list` parameter `options`
`'TIMING_OUT' | 'TIMED_OUT'` -> `'TIMING-OUT' | 'TIMED-OUT'`
effectively changes it from
`'READY' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'ABORTING' | 'ABORTED' | 'TIMING_OUT' | 'TIMED_OUT'`
to
`'READY' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'ABORTING' | 'ABORTED' | 'TIMING-OUT' | 'TIMED-OUT'`
The reason for the bug is simple — `ACT_JOB_STATUSES` has super misleading key names :)
see [ACT_JOB_STATUSES](https://github.com/apify/apify-shared-js/blob/37169fcbbd013ee45a6484adcf83ce1135057b4b/packages/consts/src/consts.ts#L30)
=> Fix RunCollectionListOptions status type

src/resource_clients/actor.ts
The object should be identical as the one in the run:
https://docs.apify.com/api/v2/act-get
vs
https://docs.apify.com/api/v2/act-run-get
=> fix(actor): add missing 'pricingInfos' field to Actor object

src/resource_clients/user.ts
Prerequisite https://github.com/apify/apify-docs/pull/1569 was merged
Questions:
1. The string -> Date conversion happens automatically for all types, right? So no need to do anything?
2. Do we use explicit `T | null` anywhere if the API returns the type or null? Seems we like to do `T?` rather
=> fix: add missing 'effectivePlatformFeatures', 'createdAt', 'isPaying' to User interface

package-lock.json, package.json
prettier is just for formatting - so it should go into devDependencies. This takes out the transitive dependency on prettier `^3.5.3` which occurs b/c it is not in devDependencies.
=> Move prettier into devDependencies

src/resource_clients/key_value_store.ts, test/key_value_stores.test.js
Add `collection` and `prefix` query params for listing key-value store keys based on https://github.com/apify/actor-whitepaper/blob/master/pages/KEY_VALUE_STORE_SCHEMA.md#api-implications
Api docs: https://github.com/apify/apify-docs/pull/1564
Api impl: https://github.com/apify/apify-core/pull/20726
=> feat: list kv store keys by collection of prefix

src/resource_clients/request_queue.ts, test/mock_server/routes/request_queues.js, test/request_queues.test.js
Implement the `unlockRequests` method in the RequestQueue client to support the new API endpoint. Update the mock server and tests to include the endpoint.
=> feat: Add unlockRequests endpoint to RequestQueue client

src/resource_clients/actor_collection.ts
Renamed option for sortBy parameter from "lastRunStartedAt" to "stats.lastRunStartedAt" to fit the [TICKET](https://app.zenhub.com/workspaces/platform-team-5f6454160d9f82000fa6733f/issues/gh/apify/apify-core/20997) specifications. Will merge when the [apify-core PR](https://github.com/apify/apify-core/pull/21731) is deployed
=> fix: Rename option for new sortBy parameter

src/resource_clients/dataset.ts, src/resource_clients/key_value_store.ts
This PR changes `expiresInMillis` to `expiresInSecs` and moves it to options in create storage content URLs:
- `KeyValueStore.createKeysPublicUrl(options)`
- `Dataset.createItemsPublicUrl(options)`
Note: I'm aware that this can potentially be breaking change, but we suppose that no one started using it yet.
More context: https://apify.slack.com/archives/C01VBUV81UZ/p1756111935325179
=> refactor!: rename expiresInMillis to expiresInSecs in create storage content URL

src/apify_client.ts, src/base/api_client.ts, src/resource_clients/actor.ts, src/resource_clients/dataset.ts, src/resource_clients/key_value_store.ts, test/datasets.test.js, test/key_value_stores.test.js
=> fix: presigned resource urls shouldn't follow `baseUrl`

package.json, src/resource_clients/actor.ts, src/resource_clients/task.ts
We want Actor developers to be able to easily test their full permission Actors with limited permissions without changing the Actor configuration for everybody or redeploying the Actor under a different name.  For that reason, we have introduced a new `forcePermissionLevel` run option. This PR adds the option to the client.
Full context here: https://github.com/apify/apify-core/pull/22681
=> feat: add forcePermissionLevel run option
